branch-defaults:
  master:
    environment: rails-beanstalk-env
    group_suffix: null
global:
  application_name: react-on-rails-devise-boilerplate
  branch: null
  default_ec2_keyname: devenv-key
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
